apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "default"
resources:
  - release.yaml
configMapGenerator:
  - name: service1
    files:
      - service1.yaml=../../../helm-values/service1/dev-config.yaml
configurations:
  - ../kustomizeconfig.yaml
